apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  ports:
    - name: tcp-53
      protocol: TCP
      port: 53
      targetPort: 53
    - name: tcp-9153
      protocol: TCP
      port: 9153
      targetPort: 9153
  loadBalancerIP: "172.17.255.1"
  type: LoadBalancer
