apiVersion: v1
kind: Service
metadata:
  name: coredns-udp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
  namespace: kube-system
spec:
  selector:
    name: coredns-udp
  ports:
    - {protocol: UDP, name: udp-53, port: 53, targetPort: 53 }
  loadBalancerIP: "172.17.255.1"
  type: LoadBalancer