apiVersion: v1
kind: Service
metadata:
  name: coredns-udp-service
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  ports:
    - name: udp-53
      protocol: UDP
      port: 53
      targetPort: 53
  loadBalancerIP: "172.17.255.1"
  type: LoadBalancer