apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # RoleBinding grants permission within a spcific namespace
metadata:
  name: jane-admin
  namespace: dev
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: jane
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: admin
