apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: enzo1920/enzo1920_kubemon:latest
          ports:
            - name: web
              containerPort: 80
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.8.0
          args: ['-nginx.scrape-uri', 'http://localhost:80/basic_status']
          ports:
            - name: exporter
              containerPort: 9113

