alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager.130.211.112.62.nip.io
    paths:
      - /

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.130.211.112.62.nip.io
    paths:
      - /

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.130.211.112.62.nip.io
    paths:
      - /

