apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
    prometheus: default
  name: app
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: app
  type: LoadBalancer
