tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

replicas: 3
resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 30m

nodeSelector:
  cloud.google.com/gke-nodepool: infra-pool
