apiVersion: v1        # Версия API
kind: Pod             # Объект, который создаем
metadata:
  name: web          # Название Pod
  labels:             # Метки в формате key: value
    app: web
spec:                 # Описание Pod
  containers:         # Описание контейнеров внутри Pod
  - name: nginx-test             # Название контейнера
    image: enzo1920/nginx-test:valve    # Образ из которого создается контейнер
    ports:
    - containerPort: 8000
  volumes:
  - name: app
    emptyDir: {}
  initContainers:
  - name: init-myservice
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
